AppEnv: prod

# 服务配置
HttpServer:
  Api:
    Port: ":12345"
  Web:
    Port: ":34567"

# 数据库配置
Mysql:
  Default:
    Host: "127.0.0.1"
    Port: 3306
    User: "root"
    Password: "123456"
    Charset: "utf8mb4"
    Databases: "skeleton"

# Redis配置
Redis:
  Host: "127.0.0.1"
  Port: 6379
  Password: ""
  Db: 10
  MaxRetries: 2   # 最大重连次数

Logs:
  GinLogName: "/runtime/logs/request.log"         #设置 gin框架的接口访问日志
  SkeletonLogName: "/runtime/logs/runtime.log"    #设置Skeleton项目骨架运行时日志文件名，注意该名称不要与上一条重复 ,避免和 gin 框架的日志掺杂一起，造成混乱。
  TextFormat: "json"                              #记录日志的格式，参数选项：console、json ， console 表示一般的文本格式
  TimePrecision: "second"                         #记录日志时，相关的时间精度，该参数选项：second  、 millisecond ， 分别表示 秒 和 毫秒 ,默认为毫秒级别
  MaxSize: 10                                     #每个日志的最大尺寸(以MB为单位）， 超过该值，系统将会自动进行切割
  MaxBackups: 7                                   #保留旧日志最大个数
  MaxAge: 15                                      #保留旧日志最大天数
  Compress: false                                 #日志备份时，是否进行压缩
